### ISSUE TITLE
\doi is an undefined control sequence

### ISSUE THREAD

**Issue by adamliter** [semprag/biblatex-sp-unified#1]
On line 257 of biblatex-sp-unified.bbx, you have `\DeclareFieldFormat{doi}{\doi{#1}}`, but `\doi` never seems to be defined anywhere.

Here's an MWE that illustrates the problem and also gives one possible way you might define `\doi`.

``` tex
\begin{filecontents*}{\jobname.bib}
@article{chomsky2013:projection,
    Author = {Chomsky, Noam},
    Doi = {10.1016/j.lingua.2012.12.003},
    Journaltitle = {Lingua},
    Issn = {0024-3841},
    Issuetitle = {Syntax and cognition: core ideas and results in syntax},
    Editor = {Rizzi, Luigi},
    Pages = {33--49},
    Title = {Problems of projection},
    Volume = {130},
    Date = {2013-06}}
\end{filecontents*}

\documentclass{article}

\usepackage[
    backend=biber,
    bibstyle=biblatex-sp-unified,
    citestyle=sp-authoryear-comp,
    maxcitenames=3,
    maxbibnames=99
]{biblatex}

\addbibresource{\jobname.bib}

%\usepackage{hyperref}
%\newcommand{\doi}[1]{\textsc{doi}: \href{http://dx.doi.org/#1}{\nolinkurl{#1}}}

\begin{document}

\nocite{*}

\printbibliography

\end{document}
```

**Comment by adamliter** [comment]
Ah, I see that you define it in `sp.cls` as `\newcommand{\doi}[1]{\url{http://dx.doi.org/#1}}`.

Still, it might be nice if the BibLaTeX style could stand on its own.

**Comment by fintelkai** [comment]
Good point. I'll look into this. Might make sense to check whether there are other such macros that belong more in the BibLaTeX style than in sp.cls.

**Comment by adamliter** [comment]
Sounds good. Thanks! And thanks for making this style publicly available, too. `:)`

**Comment by adamliter** [comment]
:+1: :smile:

**Comment by waltonpcoutinho** [comment]
Many thanks for the solution!
