### ISSUE TITLE
Title + subtitle interaction swallows punctuation

### ISSUE THREAD

**Issue by chbrown** [semprag/biblatex-sp-unified#12]
Ending a title with `.` seems to prevent the `:` from showing up when using a subtitle. E.g.:

```
At least et al.: The semantics of scalar modifiers
```

**Comment by fintelkai** [comment]
Biblatex interprets the abbreviation dot in "et al." as a sentence ending period. If the title ends in a sentence-ending punctuation, inserting the usual colon would be ugly. Suppose the title is a question "How do presuppositions work?" ... in that case we wouldn't want to insert a colon between the title and the subtitle. The solution is to signal to biblatex that the dot is not a sentence period. Two ways:

```
\title{At least et al.\isdot}
```

using the `\isdot` command of biblatex. This makes the bib-file non-portable, though, so a TeX-y solution may be better:

```
\title{At least et al.\@}
```

using the `\@` device that TeX has to disambiguate periods. See http://latex-alive.tumblr.com/post/827168808/correct-punctuation-spaces.

More tangentially relevant discussion at http://tex.stackexchange.com/questions/170547/in-biblatex-treat-periods-in-journal-as-abbreviation-dots.

[I haven't tested either of these solutions, but I'm pretty sure either will work. Please comment if they don't and I'll reopen the issue.]

**Comment by chbrown** [comment]
I tested your suggestions; both `.\isdot` and `.\@` solve the issue. Thanks for the clarification! — I added a short note about title/subtitle to [info.semprag.org/style](http://info.semprag.org/style)
