### ISSUE TITLE
What to do when conference proceedings published with an ISSN have a volume number (such as BUCLD proceedings)?

### ISSUE THREAD

**Issue by adamliter** [semprag/biblatex-sp-unified#15]
Given the guidelines in the [Unified stylesheet for linguistics](http://celxj.org/downloads/UnifiedStyleSheet.pdf), it seems like it is impossible to create a portable `.bib` entry for conference proceedings published with an ISSN that have a volume number.

Because of this, I'm wondering if it's worth revisiting the Unified stylesheet guidelines and I'm therefore also wondering if you've had a chance to see if folks would be interested in some sort of working group, @fintelkai.

Let me illustrate the problem with an example.

BUCLD proceedings are usually published in two volumes. Moreover, the proceedings are published with an ISSN, which means that they should be treated as a journal entry according to the Unified guidelines.

To get the correct output according to the Unified stylesheet guidelines with the current implementation of `biblatex-sp-unified` (2802b8743193c14a97691d4234d515881020da74), the `.bib` entry for a BUCLD proceedings paper would need to look like this:

```
@inproceedings{abarbanell2015:perspective,
  title = {Left-Right Language and Perspective Taking in {Tseltal} {Mayan} Children},
  author = {Abarbanell, Linda and Li, Peggy},
  booktitle = {Boston University Conference on Language Development (BUCLD)},
  editor = {Grillo, Elizabeth and Jepson, Kyle},
  issn = {1080-692X},
  volume = {39},
  number = {1},
  publisher = {Cascadilla Press},
  location = {Somerville, MA},
  date = {2015-09},
  pages = {1--13}
}
```

With the current implementation, this correctly produces this output:

<img width="761" alt="screen shot 2015-12-29 at 12 01 58 pm" src="https://cloud.githubusercontent.com/assets/4974404/12039208/092256ba-ae24-11e5-9ce0-4c2c62d04f9e.png">

However, as you can see if you look at the [BUCLD 39 proceedings on the web](http://www.cascadilla.com/bucld39toc.html), the volume—not the number—is 1. So a more correct (and thus better, in my opinion) way to write the `.bib` entry is as follows. 

```
@inproceedings{abarbanell2015:perspective,
  title = {Left-Right Language and Perspective Taking in {Tseltal} {Mayan} Children},
  author = {Abarbanell, Linda and Li, Peggy},
  booktitle = {Proceedings of the 39th Annual {Boston} {University} {Conference} on {Language} {Development}},
  eventtitle = {Boston University Conference on Language Development},
  eventtitleaddon = {BUCLD},
  editor = {Grillo, Elizabeth and Jepson, Kyle},
  issn = {1080-692X},
  volume = {1},
  publisher = {Cascadilla Press},
  location = {Somerville, MA},
  date = {2015-09},
  pages = {1--13}
}
```

In this case, the volume number inside of the `.bib` entry is actually correct. That is, it's volume 1 of the 2-volume proceedings. I also think it would be better to put the actual title of the book inside of `booktitle`, rather than "Boston University Conference on Language Development"; instead, this can go inside of `eventtitle` and the acronym can go inside of `eventitleaddon`, which also makes the `.bib` file more portable. This isn't a problem. It would be easy enough to change the `.bbx` file to print "`eventitlte` (`eventitleaddon`)" instead of "`booktitle`".

The main problem is that to comply with the Unified guidelines and to print conference proceedings published with an ISSN as a journal, it requires entering something in the `volume` field that is **not** the actual volume in some cases. Because the information is then wrong, this breaks the portability of the `.bib` file if you wanted to use it with another style file and should thus be avoided, at least in my opinion.

I see two possibilities for addressing this if you think it should be addressed:
1. Create a "dummy" data field that would only be used by `biblatex-sp-unified`, such as `unified-volume`. Then, the `.bbx` file could use `unified-volume` and `volume` to print "39(1)", in this case (i.e., "`unified-volume`(`volume`)". (Though it might get to be more complicated than this, as soon as you start looking at how other conference proceedings are published, not just BUCLD.) 
2. Abandon the Unified guidelines on this point (which is why I asked about the working group).

Looking forward to hearing your thoughts on this and whether you think it is something that should be addressed. Hope you're enjoying break and the holidays. Happy new year! :smile_cat:

**Comment by fintelkai** [comment]
@adamliter I'm traveling at the moment but will attend to biblatex-sp-unified in January. Thanks for raising this issue.

**Comment by adamliter** [comment]
Sounds good, @fintelkai. Happy traveling!

**Comment by chbrown** [comment]
I'm thinking this might be outside the scope of `biblatex-sp-unified`, especially now that `lx-unified-v2` is in the works.

**Comment by adamliter** [comment]
@chbrown Yes, I suppose that's probably true.

**Comment by chbrown** [comment]
In line with my previous remark, I'm closing this as out-of-scope with regard to `biblatex-sp-unified`'s goals, which is to implement the Unified stylesheet with minimal changes.

As linked above, discussion continues in https://github.com/lx-unified-v2/lx-unified-v2/issues/4

If you develop a fix that supplements the current behavior in a USL-compliant way, please submit a PR and add a comment here (mentioning me) so I can re-open this issue.
