### ISSUE TITLE
Multiple editors not abbreviated

### ISSUE THREAD

**Issue by chbrown** [semprag/biblatex-sp-unified#17]
For an `@inproceedings` entry, if there are a lot of editors (like 3+) in the `editor = {...}` field, they should be abbreviated with "et al."

But if you use a literal "et al." the resulting "(ed.)" isn't accurate; it should be "(eds.)", as it is when there are multiple editor names.

**Comment by fintelkai** [comment]
The correct way to deal with this is to set the max{bib|cite}names options when calling biblatex. sp.cls calls biblatex with these options: maxcitenames=3, maxbibnames=99. This truncates in-text citations to the first three authors, but in the bibliography all (well up to 99) authors/editors are listed. If we want to truncate long author/editor lists in the bibliography as well, we would just set maxbibnames to something palatable (3?). As soon as one does this, "et al. (eds.)" should appear as desired. 

I think we should list all editors or none. The documentation of biblatex-sp-unified includes this: 

> NB: The examples included with the Unified Style Sheet do not include the editors of the CLS proceedings volume. We agree with this practice, since the names of editors of such proceedings are often hard to get hold of.
