### ISSUE TITLE
URL dates following ISO 8601?

### ISSUE THREAD

**Issue by alecshaw** [semprag/biblatex-sp-unified#20]
Given that the Unified Stylesheet should be useable by researchers all over the world, and that this is an opinionated implementation, would it not be better to issue URL dates in the international date format of YYYY-MM-DD as defined in ISO 8601?

**Comment by fintelkai** [comment]
Thanks for the suggestion. We probably won't change this style in this regard unless and until the Unified Stylesheet gets revised (for more on that see https://github.com/lx-unified-v2/lx-unified-v2). Pending that, we might consider making the urldate display a configurable option.

**Comment by alecshaw** [comment]
Thanks for pointing me to the lx-unified-v2 repository. I'll take this suggestion over there.
