### ISSUE TITLE
Sentence case breaks with non-English languages through Polyglossia

### ISSUE THREAD

**Issue by alecshaw** [semprag/biblatex-sp-unified#22]
When `\setdefaultlanguage{}` from the `polyglossia` package is set to something other than `english` (in this case I was using `icelandic` but also tested `german`), `.bib` entries do not appear in sentence case, but rather as they were input, in this instance in title case in the `.bib`.

[EDIT] I'm going to put up a MWE, but now the whole thing is broken, so I'm stalled on the _working_ part.

**Comment by fintelkai** [comment]
This is working as intended. We use the `\MakeSentenceCase*` command of biblatex, which performs the conversion to sentence case only if the language is a version of English. Other languages typically do not have a concept of setting titles in sentence case. If you want to override this yourself, look at the biblatex documentation, specifically the `\DeclareCaseLangs*` command.

**Comment by alecshaw** [comment]
I see. Thank you!
