### ISSUE TITLE
labeldate has been renamed to labeldateparts in Biblatex 3.5 and subsequent

### ISSUE THREAD

**Issue by adamliter** [semprag/biblatex-sp-unified#23]
If you look at the [3.5 release notes](https://github.com/plk/biblatex/wiki#release-notes-for-version-35), you'll see:

> **INCOMPATIBLE CHANGE** The `labeldate` option is renamed to `labeldateparts`. The `datelabel` option is renamed to `labeldate` to provide consistency with all other date options. Backwards compatibility is provided and warnings will be issued.

Currently, trying to compile with Biblatex 3.6 gives:

```
! Package keyval Error: No value specified for labeldate.
```

This is because `labeldate` is now a key that (from the manual) "controls the format of the date  field selected with `\DeclareLabeldate`". `labeldateparts` now does what `labeldate` used to do.

More information on TeX.SX: [Why do I get the error “! Package keyval Error: No value specified for labeldate.”?](http://tex.stackexchange.com/q/330382/32888)

**Comment by adamliter** [comment]
cc @guidovw

This needs to be fixed in `biblatex-gl.bbx` and `gl-authoryear-comp.cbx` of the _Glossa_ LaTeX bundle as well.

**Comment by fintelkai** [comment]
Thanks for the catch and the fix. Much appreciated.
