### ISSUE TITLE
\printdateextralabel has been renamed to \printlabeldateextra in Biblatex 3.5 and subsequent

### ISSUE THREAD

**Issue by adamliter** [semprag/biblatex-sp-unified#24]
If you look at the [3.5 release notes](https://github.com/plk/biblatex/wiki#release-notes-for-version-35), you'll see:

> **INCOMPATIBLE CHANGE** The macro `\printdatelabelextra` [sic] has been renamed to `\printlabeldateextra` in line with the naming of all other date printing macros. Please use the new name. The old one will issue a deprecation warning.

Currently, trying to compile with Biblatex 3.6 gives:

```
! Undefined control sequence.
<argument> \printdateextralabel 
```

**Comment by adamliter** [comment]
cc @guidovw

This needs to be fixed in `biblatex-gl.bbx` of the _Glossa_ LaTeX bundle as well.

**Comment by fintelkai** [comment]
Thanks for the catch and the fix. Much appreciated.
