### ISSUE TITLE
inbook not handled correctly

### ISSUE THREAD

**Issue by timmli** [semprag/biblatex-sp-unified#35]
Bibentries of type `inbook` are not handled correctly. Say I have the following entry:
```
@inbook{wals-87,
    address = {Leipzig},
    author = {Matthew S. Dryer},
    booktitle = {The World Atlas of Language Structures Online},
    editor = {Matthew S. Dryer and Martin Haspelmath},
    publisher = {Max Planck Institute for Evolutionary Anthropology},
    title = {Order of adjective and noun},
    url = {http://wals.info/chapter/87},
    year = {2013}
}
```
 This will be oddly typeset as

> Dryer, Matthew S. 2013. Order of adjective and noun. In. The World Atlas of
Language Structures Online. Matthew S. Dryer & Martin Haspelmath (eds.).
Leipzig: Max Planck Institute for Evolutionary Anthropology. http://wals.
info/chapter/87.

Sure, I could just change the entry type, but this makes the whole thing unnecessarily error-prone. I cannot see why `inbook` shouldn't be simply treated the same as `incollection`. Therefore, what I usually do is tell Biblatex to do so:
```
\DeclareBibliographyAlias{inbook}{incollection}
```

Maybe it would be a good idea to include this in the style files already?

**Comment by fintelkai** [comment]
Sounds reasonable. We'd accept a PR along those lines.

**Comment by adamliter** [comment]
This is a bit belated, but, for what it's worth, this isn't exactly in line with the semantics that the `@inbook` entry type has. To quote from the Biblatex manual:

> Use the `@inbook` entry type for a self-contained part of a book with its own title only. It relates to `@book` just like `@incollection` relates to `@collection`. (p. 31)

And, furthermore `@collection` is described as:

> A single-volume collection with multiple, self-contained contributions by distinct authors which have their own title. The work as a whole has no overall author but it will usually have an editor. (p. 8)

Compare this to how `@book` is described:

> A single-volume book with one or more authors where the authors share credit for the work as a whole. (p. 7)

Given that WALS online is [described as](http://wals.info/) "a separate publication, edited by Dryer, Matthew S. & Haspelmath, Martin", where each chapter has different authors, it seems like it should just be in the database as an `@incolletcion` entry, not an `@inbook` entry. (I'm not sure why @timmli was opposed to changing the entry type?)

I suppose there's no serious harm in aliasing `@inbook` to `@incollection`, and it might be convenient, but it could also promote confusion about the particular semantics of `@inbook`. I'm not sure that I have a strong opinion either way, but I thought I'd point this out to see if anyone else does.

(CC: @chbrown)

**Comment by chbrown** [comment]
No, it's not the most proper/accurate solution, but I have run into the same problem as timmli, where `@inbook` seemed more appropriate than `@incollection`, but I switched to `@incollection` because it looked better.

And in the company of [`\DeclareBibliographyAlias{collection}{book}`](https://github.com/semprag/biblatex-sp-unified/blob/dc96bb7/bbx/biblatex-sp-unified.bbx#L487) and [`\DeclareBibliographyAlias{incollection}{inproceedings}`](https://github.com/semprag/biblatex-sp-unified/blob/dc96bb7/bbx/biblatex-sp-unified.bbx#L492), this alias doesn't seem to fall too far afield, hack-wise.

**Comment by adamliter** [comment]
@chbrown Fair enough, that makes sense. 😄

**Comment by fintelkai** [comment]
I agree with @chbrown. This is not a matter where `biblatex-sp-unified` should innovate something that goes beyond the Unified Style Sheet. If there should be a differentiated treatment of `@inbook` and `@incollection`, then this should be taken to the discussion of the USLv2 (https://github.com/lx-unified-v2/lx-unified-v2).

**Comment by kopeckyf** [comment]
Hi everyone,

I'm not sure whether it's ideal to alias `inbook` and `incollection`. They diverge in the roles of `editor` vs. `bookauthor`. An `@inbook` entry can have a `bookauthor` who is not the editor of the book. These cases are rare, and I didn't find treatment of them in Unified. One could resort to using `@misc` for these rare cases, but I think it would be cleaner to have separate entry types for them. There's [a definition](https://github.com/plk/biblatex/blob/8d3345f0735c23d6886cf1fb0cf6350b2c526253/tex/latex/biblatex/bbx/standard.bbx#L197) in `standard.bbx` one could import and adjust.

Best wishes,
Felix

**Comment by fintelkai** [comment]
Thanks, could you propose how an @inbook entry should be styled that is consistent with the Unified principles? Especially for a case with both a bookauthor and an editor. Coding it would then be easy enough.

**Comment by kopeckyf** [comment]
@fintelkai the usage of `@inbook` that I saw contained only a `bookauthor` and an `author`, but not an editor. In this particular instance it would not have made sense to include the `editor` information, so from this case I'm thinking that there is always either an author or an editor for `@inbook` – but I'm not sure! 

Anyway, this is how I formatted the entry which I think is in the spirit of Unified (it's an unusual, ancient source relevant to the study of Mauritian Creole):

![grafik](https://github.com/semprag/biblatex-sp-unified/assets/10461729/aa4f531c-d22e-49d2-98c8-ec7beea22620)

```latex
@inbook{Chrestien1818,
	author = {Chrestien, François},
	year = {1818},
	title = {Le lièvre et la tortue},
	booktitle = {Voyage autour du monde},
	publisher = {Pillet Aîné},
	bookauthor = {de Freycinet, Louis},
	location = {Paris},
	pages = {411--412}
}
```
