### ISSUE TITLE
The cbx files in the langsci package in TeXLive 2017 is given priority over these by XeLaTeX

### ISSUE THREAD

**Issue by apc** [semprag/biblatex-sp-unified#36]
I don't quite know what the best solution to this would be. But here's an issue I just ran into: the [langsci](https://www.ctan.org/pkg/langsci) package in CTAN (which is part of TeXLive) contains a file also named `sp-authoryearcomp.cbx`. But that file lives under `$TEXMF-DIST/tex/xelatex/` and not inside `$TEXMF-DIST/tex/latex/biblatex/`. As a result, `xelatex` gives it priority over the `cbx` file that is part of this package (assuming that file lives here: `~/Library/texmf/tex/latex/biblatex/sp-authoryear-comp.cbx` as per the instructions.)

I've currently just symlinked to the `cbx` file that is part of this package from inside `~/Library/texmf/tex/xelatex/` and that seems to do the trick.

**Comment by fintelkai** [comment]
Thank you, we're aware of the issue. It's been addressed at the langsci end. See https://github.com/langsci/latex/issues/50 and https://github.com/langsci/CTAN/issues/2. If you update TeXLive (via the TeX Live Utility, for example), you will get a version of langsci that doesn't have the offending files.
