### ISSUE TITLE
.bst?

### ISSUE THREAD

**Issue by HedvigS** [semprag/biblatex-sp-unified#37]
Are there any plans on making a .bst file, so that one doesn't need to use Biber? Or have I misunderstood something? Or should I just get on the Biber-train.. ?

**Comment by fintelkai** [comment]
Not sure I understand your question. As the documentation says, there's a bst file corresponding to the Unified Stylesheet: http://celxj.org/downloads/unified.bst. This can be used as a drop-in for a conventional bibtex/natbib setup for authors who want to follow the Unified Stylesheet but are not ready for biber/biblatex.

`biblatex-sp-unified` is a biber/biblatex-based implementation of the Unified Stylesheet. It is used by *Semantics & Pragmatics* in production, and in modified form by Language Science Press. And yes, it's biber/biblatex-based.

Are you trying to prepare an article for submission? If so, the more important work goes into preparing a good .bib file. The bibliographic styling is secondary and there are many good options depending on your needs and the venues you're submitting to.

**Comment by HedvigS** [comment]
Ah, I'm stupid. Thank you.
