### ISSUE TITLE
\let\citep\parencite disables natbib compatbility mode

### ISSUE THREAD

**Issue by moewew** [semprag/biblatex-sp-unified#40]
The definitions in
https://github.com/semprag/biblatex-sp-unified/blob/dc96bb703a018b0b3a2886d14a54ccb58052044a/cbx/sp-authoryear-comp.cbx#L291-L302
are a bit too aggressive, as can be seen in https://github.com/langsci/latex/issues/75. In particular the `\let\citep\parencite` disables `biblatex`'s `natbib` compatibility mode for `\citep`, but the same holds for `\citet` and `\citealt`.

I'm also not fond of `\newcommand{\pgcitep}[2]{(\cite{#1}:~#2)}`, `\newcommand{\pgcitet}[2]{\citeauthor{#1} (\citeyear{#1}:~#2)}` and friends. I'm not entirely sure what it is supposed to do, but it looks as though this is basically `\parencite[13]{sigfridsson}`/`\textcite[12]{sigfridsson}` (with the postnote delimiter changed appropriately). Using `\cite...` commands in a `\newcommand` normally destroys pre- and postnotes. And stuffing several `\cite....`s in one `\newcommand` means that you can't cite multiple keys. So I consider this bad form even if it gives the desired output in all use cases you can think of.

**Comment by fintelkai** [comment]
Thanks for pointing this out. biblatex-sp-unified was written by a rank amateur (me) and help like this is very much appreciated. We'll see what we can do.

**Comment by alecshaw** [comment]
Hi everyone. I'm working on resolving this, and for now removing the `\let\citep\parencite` line resolves the issue in https://github.com/langsci/latex/issues/75. What was the motivation for these `\let` declarations, and could we scrap them?

**Comment by fintelkai** [comment]
Honestly, the motivation is probably lost in the mist of time. It may be 
that at the time, we were not fully aware of the natbib compatibility 
option/code.

-- Kai.

**Comment by moewew** [comment]
I would just drop the entire block mentioned in my first post. The `natbib` compatibility mode can automatically take care of `\citealt`, `\Citealt` `\citet`, `\Citet`, `\citep`, `\Citep`. 

The only drawback here is that your style can not enable the `natbib` compatibility mode itself, since the `natbib` option can only be used at loading time. The user will have to do that consciously herself. This may be a problem if you pride yourselves on providing all of these commands out of the box, but should not be dramatic, since it is generally known that one needs the `natbib` option to make use of these `natbib` names.

`\pgcitep` and friends are not defined by the `natbib` compatibility mode and so they don't interfere there and do not cause the problems from https://github.com/langsci/latex/issues/75. But as I said above, these constructions are a bit meh.

**Comment by fintelkai** [comment]
The new version of the citation style does not overwrite biblatex's compatibility code. The legacy macros `\pgcitep` and siblings are still in there, but we'll retire them at some point. In other news, I finally submitted the package to CTAN under the proposed name biblatex-unified. The style files are now called unified.{bbx,cbx} and they can be called via the style=unified option.
