### ISSUE TITLE
CTAN upload

### ISSUE THREAD

**Issue by sieversMartin** [semprag/biblatex-sp-unified#42]
Is there any (good) reason, why you haven't uploaded your package to CTAN yet? It would be a great benefit to everyone not having to install the package manually.

If it is only a question of format and/or time, I'll be glad to help you.

**Comment by fintelkai** [comment]
The good reason is precisely that we haven’t had time to look into exactly what’s needed (although I’ve collected some material) and then to do that. It’s on the summer bucket list but if you can help, we’d be very happy to get pull requests that get the package into the right shape for CTAN submission.

**Comment by sieversMartin** [comment]
I added a script to use `ctanify` to wrap up an archive.

`README.md` should contain versioning and licensing information as well for CTAN

**Comment by fintelkai** [comment]
Yes, thank you. I think the entire documentation needs to be checked and edited to reflect the CTAN organization of files etc. So, that's still to do. In general, the package should follow the biblatex style conventions for CTAN packages, which I'm not sure it does.

I will not have significant brain cycles to devote to this until after June 3. But I'm happy that there's enthusiasm and support.

**Comment by fintelkai** [comment]
Today, I finally submitted the package to CTAN under the proposed name biblatex-unified. The style files are now called unified.{bbx,cbx} and they can be called via the style=unified option. Thanks, @alecshaw and @sieversMartin for the help (oh so long ago).
