### ISSUE TITLE
Single word for style name

### ISSUE THREAD

**Issue by alecshaw** [semprag/biblatex-sp-unified#43]
Seeing issue #42 and in the interest of preparing a release for CTAN, I want to propose a change to the filenames and see what everyone has to say.

In my own installation of the stylesheet, I symlink from my local copy of the repository to the appropriate location in the TeX directory structure. I also change the filenames to `unified.bbx` and `unified.cbx`. I prefer `style=unified` as a package option to `biblatex` over the two different filenames currently used.

Is there interest in finding a single word for both the citation and bibliography files?

**Comment by fintelkai** [comment]
In principle, `unified.{bbx,cbx}` would be a fine choice. But CELxJ distributes a `unified.bst` bibtex style, which was prepared by Bridget Samuels based on `sp.bst`. Would this be confusing?

**Comment by sieversMartin** [comment]
If the package name is `biblatex-unified` or `biblatex-sp-unified` then naming the style itself just `unified` sounds good to me.

**Comment by fintelkai** [comment]
Before the CTAN upload, we should make sure that the naming choices are in concert with biblatex practices.

**Comment by sieversMartin** [comment]
Fully agree.

**Comment by fintelkai** [comment]
Today, I finally submitted the package to CTAN under the proposed name `biblatex-unified`. The style files are now called `unified.{bbx,cbx}` and they can be called via the `style=unified` option. Thanks, @alecshaw and @sieversMartin for the help (oh so long ago).
