### ISSUE TITLE
non-separable ampersand

### ISSUE THREAD

**Issue by art-keidan** [semprag/biblatex-sp-unified#50]
Please, glue the "&" symbol to the preceding Author's name, otherwise it would be sometimes sent to the next line, which looks ugly:
![Ampersand](https://user-images.githubusercontent.com/18039080/115992007-ab8caf00-a5cb-11eb-9019-525dac726745.png)

**Comment by fintelkai** [comment]
@art-keidan: I think the following might work, so you could try that in your preamble:

```
\renewcommand*{\finalnamedelim}{\addnbspace\&\addspace}
\renewcommand*{\finallistdelim}{\addnbspace\&\addspace}
```

Alternatively, you could check out the `develop` branch of this repo and see whether it fixes the problem.

**Comment by art-keidan** [comment]
Thank you, this works fine to me!

**Comment by fintelkai** [comment]
This is now incorporated into v1.1 of `biblatex-unified`.

**Comment by art-keidan** [comment]
Thanks again.
