### ISSUE TITLE
Colon before pages

### ISSUE THREAD

**Issue by art-keidan** [semprag/biblatex-sp-unified#54]
I am so used to write a colon after the journal volume+number, before pages. Would it be possible to enable such an option?  Or, is there a workaround?

**Comment by fintelkai** [comment]
1. `biblatex-unified` implements the Unified Stylesheet, which doesn't use a colon.

2. A quick but ugly workaround: in your preamble after loading `biblatex-unified`, redefine the article driver and the `bibpagespunct` command:

> ```latex
> \DeclareBibliographyDriver{article}{%
>   \usebibmacro{bibindex}%
>   \usebibmacro{begentry}%
>   \usebibmacro{author/translator+others}%
>   \setunit{\labelnamepunct}\newblock
>   \usebibmacro{title}%
>   \newunit
>   \printlist{language}%
>   \newunit\newblock
>   \usebibmacro{byauthor}%
>   \newunit\newblock
>   \usebibmacro{bytranslator+others}%
>   \newunit\newblock
>   \printfield{version}%
>   \newunit\newblock
>   \usebibmacro{journal+issuetitle+editor}%
>   \bibpagespunct
>   \usebibmacro{note+pages}%
>   \newunit\newblock
>   \iftoggle{bbx:isbn}
>     {\printfield{issn}}
>     {}%
>   \newunit\newblock
>   \usebibmacro{doi+eprint+url}%
>   \newunit\newblock
>   \usebibmacro{addendum+pubstate}%
>   \setunit{\bibpagerefpunct}\newblock
>   \usebibmacro{pageref}%
>   \newunit\newblock
>   \iftoggle{bbx:related}
>     {\usebibmacro{related:init}%
>      \usebibmacro{related}}
>     {}%
>   \usebibmacro{finentry}}
> \renewcommand*{\bibpagespunct}{\addcolon\addspace}
> ```

3. Over the winter, a refactoring of `unified.bbx` is planned, which will probably make such customizations easier. So, stay tuned.
