### ISSUE TITLE
What to do when issuetitle and editor are present in an @article entry?

### ISSUE THREAD

**Issue by adamliter** [semprag/biblatex-sp-unified#8]
With the current implementation of `biblatex-sp-unified` (77705180f97bcc4489e62a23b5a8eba6719a21f3), the MWE given below will lead to this output in the References section:

> Chomsky, Noam. 2013. Problems of projection. _Lingua_ 130(1): _Syntax and cognition: Core ideas and results in syntax_. Luigi Rizzi (ed.). 33–49. `http://dx.doi.org/10.1016/j.lingua.2012.12.003`.

I have a few questions about this, and at the risk of being perhaps a bit chatty and a bit off-topic for a GitHub Issue, I feel like I should also be transparent about why I'm asking. :smile: 

A friend and I are working on a project that we're calling [Lingbib](https://github.com/lingbib/lingbib). It's not ready to see the light of day yet, but the idea is to develop a GitHub repo where people can collectively contribute to a single `.bib` file for all of linguistics. We think it's a waste of time for people to do this individually, and we also think this will ensure greater accuracy of the information in the `.bib` file, since multiple sets of eyes will be looking at it.

We want the `.bib` file to ultimately be as portable as possible. This is why I proposed the changes for the `@inproceedings` driver that I did. If the entry really is an `@inproceedings` entry, then the `.bib` file will be portable and usable with other styles if it is entered into the database as an `@inproceedings` entry (not an `@article` entry).

Related to portability of the `.bib` file is the issue of ensuring that all available bibliographic information that is available is included in the entry in the `.bib` file. Some styles might call for more information than others, and so we want that information to be available in the `.bib` file should someone want to use the `.bib` file with a style that calls for more information.

So that's the background of why I'm asking this question. :smile: 

The Chomsky (2013) reference was part of a _Lingua_ special issue, so there is an `Issuetitle` (and `Issuesubtitle`) as well as an `Editor` for this `@article` entry.

Given that you've largely adopted the drivers from `standard.bbx`, there is more information printed than the Unified Style Sheet strictly calls for. So here are the questions that I have:
1. Strictly speaking, the Unified Style Sheet doesn't say anything about this extra information, so I'm not sure what the best thing to do would be. Since it doesn't explicitly call for it, I'm assuming that it should just be omitted. Do you have any insight into what might be best to do in order to conform to the Unified Style Sheet guidelines?
2. If the information should not be omitted, how should it be formatted? I'm guessing that it would probably be different than above. (Of course, the antecedent of this conditional could very well be false.)
3. I was also wondering if you'd be open to me opening more issues like this. Part of the reason that Lingbib isn't ready to see the light of day yet is because we want to be able to distribute it with a Biblatex style that conforms to the Unified Style Sheet so that people can actually use the `.bib` file out of the box. If you'd rather not have me opening issues because of this, I'm happy to develop an implementation on my own, probably using yours as the basis. However, if you're open to me opening issues because of our Lingbib project, then you'll probably be seeing more of me. :smile: I don't want to bombard and overwhelm you, though, so I figured I should probably ask.

At any rate, depending on what you think about questions (1) and (2), I've developed an `issueandeditor` option that defaults to `false` in 2bd733dad649692edb6a31e81461620d56743782. If it is `false`, the information is not printed. If it is `true`, the information is printed and shows up exactly as described above (given the reliance on the `@article` driver of `standard.bbx`).

But there might be a better way of handling this case, depending on your answers to (1) and (2). Or if you'd prefer to not handle this case at all and you'd rather just have people not enter this information into the `.bib` file, that's fine, too. Then you can just close this issue, and I'll probably start working on a different implementation to be distributed with Lingbib.

Sorry for being a bit chatty and perhaps off-topic. :smile: 
## MWE

``` tex
% !TEX encoding = UTF-8 Unicode
% !TEX TS-program = arara
% arara: pdflatex
% arara: biber
% arara: pdflatex

\begin{filecontents*}{\jobname.bib}
@article{chomsky2013:projection,
    Abstract = {With the crystallization of the ``generative enterprise'' half a century ago, two concepts became salient: the initial state and final states of the language faculty, respectively, UG (the genetic component) and I-languages. Since then inquiry has gained far greater scope and depth. It has also led to sharpening of fundamental principles of language. At first, descriptive adequacy appeared to require rich and complex assumptions about UG. A primary goal has always been to overcome this deficiency. Core properties of concern have included compositionality, order, projection (labeling), and displacement. Early work assigned the first three to phrase structure rules and the last to the transformational component. Simplification of computational procedures suggests that compositionality and displacement (along with the ``copy theory'') fall together while order may be a reflex of sensorimotor externalization, conclusions that have far-reaching consequences. As for labeling, minimal computation restricts options to the few that have considerable empirical support.},
    Author = {Chomsky, Noam},
    Doi = {10.1016/j.lingua.2012.12.003},
    Journaltitle = {Lingua},
    Issn = {0024-3841},
    Issuetitle = {Syntax and cognition},
    Issuesubtitle = {Core ideas and results in syntax},
    Editor = {Rizzi, Luigi},
    Langid = {english},
    Langidopts = {variant=american},
    Pages = {33--49},
    Title = {Problems of projection},
    Volume = {130},
    Number = {1},
    Date = {2013-06}}
\end{filecontents*}

\documentclass{article}

\usepackage[
    backend=biber,
    bibstyle=biblatex-sp-unified,
    citestyle=sp-authoryear-comp,
    maxcitenames=3,
    maxbibnames=99%,
    %issueandeditor=true
]{biblatex}
\addbibresource{\jobname.bib}

\begin{document}
\textcite{chomsky2013:projection}
\printbibliography
\end{document}
```

**Comment by fintelkai** [comment]
1. There's little I enjoy chatting about more than linguistics-related geekery. So, chat ahead. This is our github repo and we can do what we want with it.
2. Your lingbib project sounds great. I'm cc'ing Chris Brown, who's been working on a similar idea. I don't know what the status of that is, but maybe you guys should talk.
3. I completely agree that portability of bib-files is important. Ideally, there would be very few (or none) idiosyncratic policies about how a bib-entry should look. So, biblatex-sp-unified should be prepared to deal with a surfeit of information in the bib-entry.
4. The Unified Stylesheet is quite under-specified in many ways. I don't think the group who came up with it is a going concern, so it's a matter of someone(s) taking leadership. There is an overlapping project started by Martin Haspelmath ("The Generic Style Rules for Linguistics", http://www.eva.mpg.de/fileadmin/content_files/staff/haspelmt/pdf/GenericStyleRules.pdf). [This of course brings to mind https://xkcd.com/927/.] I know that Stefan Müller of Language Science Press is eager to get some more standardization in place. Maybe, we need to stand up a working group. Let me poke around a bit.
5. I don't have strong feelings about issue titles and editors for special issues of journals. My impression is that linguistics bibliographies usually don't include that information, though. So, for now, I'm inclined to decree that biblatex-sp-unified should ignore that info. So, that means that your solution seems right, at least for now. I'll look at it and presumably accept the PR when I have some time.

**Comment by adamliter** [comment]
> Your lingbib project sounds great. I'm cc'ing Chris Brown, who's been working on a similar idea. I don't know what the status of that is, but maybe you guys should talk.

Awesome! Kenneth—the friend who is working on the project with me—and I tried searching the internet prior to starting work on the project to see if we could find anyone else who had similar ideas or had already started work on a similar project. We didn't see anything, but if @chbrown has been working on something similar, it'd be great to talk as soon as possible and hopefully collaborate on something, rather then reduplicating effort. I'm glad I brought this up! :smile: 

> The Unified Stylesheet is quite under-specified in many ways. I don't think the group who came up with it is a going concern, so it's a matter of someone(s) taking leadership. There is an overlapping project started by Martin Haspelmath ("The Generic Style Rules for Linguistics", http://www.eva.mpg.de/fileadmin/content_files/staff/haspelmt/pdf/GenericStyleRules.pdf). [This of course brings to mind https://xkcd.com/927/.] I know that Stefan Müller of Language Science Press is eager to get some more standardization in place. Maybe, we need to stand up a working group. Let me poke around a bit.

Thanks! I'll check out Martin Haspelmath's project. And yes, the idea of a working group sounds useful. Let me know what happens after you poke around a bit. Another relevant person to involve might be Alan Munn, at least for TeXpertise, if nothing else. If a working group were to start, I could bother him and see if he's interested and has the time. He is rather busy, but I'm guessing he might be interested.

> I don't have strong feelings about issue titles and editors for special issues of journals. My impression is that linguistics bibliographies usually don't include that information, though. So, for now, I'm inclined to decree that biblatex-sp-unified should ignore that info. So, that means that your solution seems right, at least for now. I'll look at it and presumably accept the PR when I have some time.

Okay, I'll actually open a PR, then. Right now the commit is just in a branch on my fork. Thanks! :smile_cat:

**Comment by fintelkai** [comment]
I've merged your PR. Closing this issue, but we will follow up on collaboration on the broader issues raised.

**Comment by adamliter** [comment]
> I've merged your PR. Closing this issue, but we will follow up on collaboration on the broader issues raised.

:+1: Thanks!
